#!/bin/sh

SCRIPT_DIR="`dirname $0`"

MODULES_LIST="ath ath_pci wlan wlan_acl wlan_amrr wlan_ccmp wlan_rssadapt wlan_tkip wlan_wep wlan_xauth bwn mwl wi wpi"

for i in ${MODULES_LIST}; do
	echo "entering ${i}"
	PPWD="`pwd`"
	cd ${i} || exit 1
	${SCRIPT_DIR}/build_module $@ || exit 1
	echo ".. back to ${PPWD}"
	cd ${PPWD}
done
