#!/bin/sh

MODULES_LIST="ath ath_pci wlan wlan_acl wlan_amrr wlan_ccmp wlan_rssadapt wlan_tkip wlan_wep wlan_xauth"

for i in ${MODULES_LIST}; do
	echo "entering ${i}"
	PPWD="`pwd`"
	cd ${i} || exit 1
	/home/adrian/bin/build $@ || exit 1
	echo ".. back to ${PPWD}"
	cd ${PPWD}
done
